### ISSUE TITLE
compile against scala 2.13.3 & sjs 1.2.0

### ISSUE THREAD

**Issue by sidnt** [scommons/scommons-react-native#32]
Depends on this one: https://github.com/shogowada/scalajs-reactjs/issues/38

**Comment by myyk** [comment]
Looks like the change was made in https://github.com/scommons/scalajs-reactjs. Maybe it's possible now?

**Comment by viktor-podzigun** [comment]
@myyk there is still one transitive dependency (quill) that should be cross compiled to Scala 2.13/Scala.js 1.1+ first:
https://github.com/getquill/quill/issues/2175

And there is a [PR](https://github.com/getquill/quill/pull/2167) for it already, so please, up-vote (👍 ), so it gets more attention then.

**Comment by viktor-podzigun** [comment]
Ok, it looks like that `scommons-react-native` modules do not directly depend on `quill-sql` module (its rather nice to have), so I think it will be possible now to cross-compile to Scala.js 1.1+.
